git clone --recursive https://mirror.ghproxy.com/github.com/alecthomas/chroma
git clone --recursive https://mirror.ghproxy.com/github.com/armon/go-radix
git clone --recursive https://mirror.ghproxy.com/github.com/aws/aws-sdk-go
git clone --recursive https://mirror.ghproxy.com/github.com/bep/debounce
git clone --recursive https://mirror.ghproxy.com/github.com/bep/gitmap
git clone --recursive https://mirror.ghproxy.com/github.com/bep/golibsass
git clone --recursive https://mirror.ghproxy.com/github.com/bep/tmc
git clone --recursive https://mirror.ghproxy.com/github.com/BurntSushi/locker
git clone --recursive https://mirror.ghproxy.com/github.com/BurntSushi/toml
git clone --recursive https://mirror.ghproxy.com/github.com/cpuguy83/go-md2man
git clone --recursive https://mirror.ghproxy.com/github.com/danwakefield/fnmatch
git clone --recursive https://mirror.ghproxy.com/github.com/disintegration/gift
git clone --recursive https://mirror.ghproxy.com/github.com/dustin/go-humanize
git clone --recursive https://mirror.ghproxy.com/github.com/fsnotify/fsnotify
git clone --recursive https://mirror.ghproxy.com/github.com/gobwas/glob
git clone --recursive https://mirror.ghproxy.com/github.com/gorilla/websocket
git clone --recursive https://mirror.ghproxy.com/github.com/hashicorp/golang-lru
git clone --recursive https://mirror.ghproxy.com/github.com/hashicorp/hcl
git clone --recursive https://mirror.ghproxy.com/github.com/jdkato/prose
git clone --recursive https://mirror.ghproxy.com/github.com/kr/pretty
git clone --recursive https://mirror.ghproxy.com/github.com/kyokomi/emoji
git clone --recursive https://mirror.ghproxy.com/github.com/magiconair/properties
git clone --recursive https://mirror.ghproxy.com/github.com/markbates/inflect
git clone --recursive https://mirror.ghproxy.com/github.com/mattn/go-isatty
git clone --recursive https://mirror.ghproxy.com/github.com/mattn/go-runewidth
git clone --recursive https://mirror.ghproxy.com/github.com/miekg/mmark
git clone --recursive https://mirror.ghproxy.com/github.com/mitchellh/hashstructure
git clone --recursive https://mirror.ghproxy.com/github.com/mitchellh/mapstructure
git clone --recursive https://mirror.ghproxy.com/github.com/muesli/smartcrop
git clone --recursive https://mirror.ghproxy.com/github.com/nicksnyder/go-i18n
git clone --recursive https://mirror.ghproxy.com/github.com/niklasfasching/go-org
git clone --recursive https://mirror.ghproxy.com/github.com/olekukonko/tablewriter
git clone --recursive https://mirror.ghproxy.com/github.com/pelletier/go-toml
git clone --recursive https://mirror.ghproxy.com/github.com/pkg/errors
git clone --recursive https://mirror.ghproxy.com/github.com/PuerkitoBio/purell
git clone --recursive https://mirror.ghproxy.com/github.com/PuerkitoBio/urlesc
git clone --recursive https://mirror.ghproxy.com/github.com/rogpeppe/go-internal
git clone --recursive https://mirror.ghproxy.com/github.com/russross/blackfriday
git clone --recursive https://mirror.ghproxy.com/github.com/rwcarlsen/goexif
git clone --recursive https://mirror.ghproxy.com/github.com/spf13/afero
git clone --recursive https://mirror.ghproxy.com/github.com/spf13/cast
git clone --recursive https://mirror.ghproxy.com/github.com/spf13/cobra
git clone --recursive https://mirror.ghproxy.com/github.com/spf13/fsync
git clone --recursive https://mirror.ghproxy.com/github.com/spf13/jwalterweatherman
git clone --recursive https://mirror.ghproxy.com/github.com/spf13/pflag
git clone --recursive https://mirror.ghproxy.com/github.com/spf13/viper
git clone --recursive https://mirror.ghproxy.com/github.com/tdewolff/minify
git clone --recursive https://mirror.ghproxy.com/github.com/tdewolff/parse
git clone --recursive https://mirror.ghproxy.com/github.com/yuin/goldmark
git clone --recursive https://mirror.ghproxy.com/github.com/yuin/goldmark-highlighting
git clone --recursive https://mirror.ghproxy.com/go.opencensus.io
git clone --recursive https://mirror.ghproxy.com/go.uber.org/atomic
git clone --recursive https://mirror.ghproxy.com/gocloud.dev
git clone --recursive https://mirror.ghproxy.com/golang.org/x/image
git clone --recursive https://mirror.ghproxy.com/golang.org/x/net
git clone --recursive https://mirror.ghproxy.com/golang.org/x/oauth2
git clone --recursive https://mirror.ghproxy.com/golang.org/x/sync
git clone --recursive https://mirror.ghproxy.com/golang.org/x/sys
git clone --recursive https://mirror.ghproxy.com/golang.org/x/text
git clone --recursive https://mirror.ghproxy.com/golang.org/x/xerrors
git clone --recursive https://mirror.ghproxy.com/google.golang.org/api
git clone --recursive https://mirror.ghproxy.com/google.golang.org/genproto
git clone --recursive https://mirror.ghproxy.com/gopkg.in/ini.v1
git clone --recursive https://mirror.ghproxy.com/gopkg.in/yaml.v2

